[Variables]
Key=
;The Dark Sky API key.
;You have to create an account on darksky.net and get a free API key to be able to use this.

WeatherLocation=
;Just put your address or the name of the place (school, company, etc.) here.
;Please check the log to see if the skin got the right location.

WeatherUnits=c
;NOTE: You can use both capital or lowercase for the display.
;The units for the weather info. Valid values are:
;f,F - Imperial units.
;c,C - Metric units.

Language=en
;Supported values and thus languages (ordered alphabetically) are: 
;ar - Arabic, az - Azerbaijani, be - Belarusian, bg - Bulgarian, bn - Bengali
;bs - Bosnian, ca - Catalan, cs - Czech, da - Danish, de - German, el - Greek
;en - English, eo - Esperanto, es - Spanish, et - Estonian, fi - Finnish
;fr - French, he - Hebrew, hi - Hindi, hr - Croatian, hu - Hungarian, id - Indonesian
;is - Icelandic, it - Italian, ja - Japanese, ka - Georgian, kn - Kannada, ko - Korean
;kw - Cornish, lv - Latvian, ml - Malayam, mr - Marathi, nb - Norwegian Bokmål
;nl - Dutch, no - Norwegian Bokmål (alias for nb), pa - Punjabi, pl - Polish
;pt - Portuguese, ro - Romanian, ru - Russian, sk - Slovak, sl - Slovenian, sr - Serbian
;sv - Swedish, ta - Tamil, te - Telugu, tet - Tetum, tr - Turkish, uk - Ukrainian
;ur - Urdu, zh - simplified Chinese, zh-tw - traditional Chinese

;================================================

;Increase or decrease this value to make the skin bigger or smaller.
;A scale of "2.00" will be 4x the area.
Scale=0.42
Scroll=false
ScaleChange=0.02

;================================================

TextColor1=255,255,255
TextColor2=255,255,255
;Enter the color for the text and vector icons here.
;Valid values are formatted "RRR, GGG, BBB" with values of 0 - 255.
